# Generated by Django 5.2.4 on 2025-10-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0006_ordencompra_archivo_soporte_ordencompra_tipo_soporte'),
        ('usuarios', '0010_user_puede_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAnticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Proceso'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('archivo_zip', models.FileField(blank=True, null=True, upload_to='expedientes/')),
                ('tracking_text', models.TextField(blank=True, null=True)),
                ('contabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_anticipo', to='usuarios.user')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_anticipo', to='compras.ordencompra')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
