# Generated by Django 5.2.7 on 2025-11-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('usuarios', '0010_user_puede_contabilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudanticipo',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='solicitudanticipo',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='solicitudanticipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitudanticipo',
            name='contabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_contabilidad', to='usuarios.user'),
        ),
        migrations.AlterField(
            model_name='solicitudanticipo',
            name='estado',
            field=models.CharField(choices=[('E', 'En Proceso'), ('F', 'Finalizado')], default='E', max_length=1),
        ),
    ]
