# Generated by Django 5.2.7 on 2025-11-04 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_solicitudanticipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudanticipo',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
