# Generated by Django 5.2.8 on 2025-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_solicitudanticipo_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudanticipo',
            name='portada_pdf',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/portadas/'),
        ),
    ]
