# Generated by Django 5.2.8 on 2025-11-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_solicitudanticipo_portada_pdf'),
        ('usuarios', '0010_user_puede_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudanticipo',
            name='zip_descargado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudanticipo',
            name='zip_descargado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudanticipo',
            name='zip_descargado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zips_descargados', to='usuarios.user'),
        ),
    ]
