# Generated by Django 5.2.4 on 2025-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puede_compras',
            field=models.BooleanField(default=False),
        ),
    ]
