# Generated by Django 5.2.4 on 2025-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_puede_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puede_requisiciones',
            field=models.BooleanField(default=False),
        ),
    ]
