# Generated by Django 5.2.4 on 2025-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_puede_requisiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puede_aprobar',
            field=models.BooleanField(default=False),
        ),
    ]
