# Generated by Django 5.2.4 on 2025-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_puede_aprobar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
