# Generated by Django 5.2.4 on 2025-09-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_user_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='es_gerente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ceco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.ceco'),
        ),
    ]
