# Generated by Django 5.2.4 on 2025-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_ceco_user_es_gerente_user_ceco'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
