# Generated by Django 5.2.4 on 2025-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_user_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_comprador',
            field=models.CharField(blank=True, choices=[('ferreteria', 'Ferretería'), ('suministros', 'Suministros'), ('medicina', 'Medicina'), ('repuestos', 'Repuestos'), ('insumos', 'Insumos')], max_length=50, null=True),
        ),
    ]
