# Generated by Django 5.2.4 on 2025-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_user_tipo_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puede_contabilidad',
            field=models.BooleanField(default=False),
        ),
    ]
