# Generated by Django 5.2.4 on 2025-07-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_user_puede_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('archivo', models.FileField(upload_to='requisiciones/')),
                ('archivo_aprobacion', models.FileField(blank=True, null=True, upload_to='aprobaciones/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField()),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('N', 'Negada')], default='P', max_length=1)),
                ('creador_req', models.CharField(blank=True, max_length=100, null=True)),
                ('importancia', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgente')], default='N', max_length=1)),
                ('directivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_recibidas', to='usuarios.user')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='usuarios.user')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
