# Generated by Django 5.2.4 on 2025-09-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('usuarios', '0007_ceco_user_es_gerente_user_ceco'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='ceco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='usuarios.ceco'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='estado_preaprobacion',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('N', 'Negada')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_preaprobadas', to='usuarios.user'),
        ),
    ]
