# Generated by Django 5.2.4 on 2025-09-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_requisicion_ceco_requisicion_estado_preaprobacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_orden', models.FileField(upload_to='ordenes_compra/')),
                ('archivo_cuadro_comparativo', models.FileField(upload_to='cuadros_comparativos/')),
                ('archivo_presupuesto', models.FileField(upload_to='presupuestos/')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('N', 'Rechazada')], default='P', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requisicion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra', to='compras.requisicion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
