# Generated by Django 5.2.4 on 2025-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
