# Generated by Django 5.2.4 on 2025-09-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordencompra_fecha_aprobacion_and_more'),
        ('usuarios', '0007_ceco_user_es_gerente_user_ceco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='creador_req',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='usuario_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_compras', to='usuarios.user'),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_creadas', to='usuarios.user'),
        ),
    ]
