# Generated by Django 5.2.4 on 2025-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_requisicion_creador_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_soporte',
            field=models.FileField(blank=True, null=True, upload_to='soportes/'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_soporte',
            field=models.CharField(blank=True, choices=[('nota', 'Nota de recepción'), ('factura', 'Factura')], max_length=10, null=True),
        ),
    ]
