# Generated by Django 5.2.4 on 2025-10-03 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_ordencompra_archivo_soporte_ordencompra_tipo_soporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='compras.requisicion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
