# Generated by Django 5.2.4 on 2025-10-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_requisicioncomentario'),
        ('usuarios', '0010_user_puede_contabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicioncomentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.user'),
        ),
    ]
