# Generated by Django 5.2.7 on 2025-11-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_requisicioncomentario_autor'),
        ('usuarios', '0010_user_puede_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.user')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='compras.ordencompra')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
